spring:
  profiles: dev
server:
  port: 7000
---
spring:
  profiles: qa
server:
  port: 7001
---
spring:
  profiles:
    active: dev
---
management:
  security:
    enabled: false
---
logging:
  level:
    org.springframework.web: ERROR
    com.aa: DEBUG
email: onlyankur@gmail.com
thread-pool: 10
---
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
management:
  endpoint:
    health:
      show-details: "ALWAYS"

#Spring boot Admin server
#To connect to spring boot admin server since spring boot admin server has spring security enabled.
spring:
  boot:
    admin:
      client:
        url: http://localhost:9000/
        username: user
        password: 8ae0841c-b7d2-4409-a37c-64b7a3f33777
